environment:
  matrix:
  - channel: stable
  - channel: beta
  - channel: nightly
platform:
- x86
- x64
install:
- ps: If($env:platform -eq "x64") { $env:target = "x86_64-pc-windows-msvc"; $env:install_dir = "C:\Program Files\Rust" } Else { $env:target = "i686-pc-windows-msvc"; $env:install_dir = "C:\Program Files (x86)\Rust" }
- ps: $env:rust_installer = ([System.Text.Encoding]::ASCII.GetString((Invoke-WebRequest "https://static.rust-lang.org/dist/channel-rust-${env:channel}").Content).Split("`n") | Select-String $env:target | Select-String exe).ToString()
- ps: Write-Output "Installing ${env:rust_installer}"
- ps: Start-FileDownload "https://static.rust-lang.org/dist/${env:rust_installer}" -FileName rust_installer.exe
- rust_installer.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
- SET PATH=%PATH%;C:\Program Files\Rust\bin
- rustc -vV
- cargo -vV
build_script:
- cargo build --verbose
test_script:
- cargo test --verbose
- cargo bench --verbose
- cargo doc --verbose
