[package]
name = "roboime-next-cli"
version = "0.1.0"
authors = ["Jan Segre <jan@segre.in>"]

[[bin]]
name = "roboime-next-cli"
path = "src/main.rs"
test = false
doc = false

[dependencies]
roboime-next = { path = ".." }
